version: '3.8'

# Services
services:
  # frontend service
  spa:
    build:
      context: .
      args:
        project_name: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    working_dir: /var/www/${PROJECT_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./spa:/var/www/${PROJECT_NAME}:rw
    networks:
      - spa-network
# Networks
networks:
  spa-network:
    name: spa-network
    driver: bridge
# Volumes
volumes:
  spa: